### ISSUE TITLE
Enquiry about the api

### ISSUE THREAD

**Issue by casualGamer-dev** [Lavish883/LokiStream-Lite#4]
Heyo Can you please tell me what api you used

**Comment by Lavish883** [comment]
> Heyo Can you please tell me what api you used

Yeah sure bro, I made it myself. There really isn't any documentation on it. But it's called https://takemyassm3u8maker.herokuapp.com/ . For how to use it you probably have to use this app's source code. Since I made the api like a year ago when I wasn't too experienced in programming I don't have much documentation on it. If you have any other questions. I would be happy to answer.

**Comment by casualGamer-dev** [comment]
can you share the code
i want to make a graphql version of it

**Comment by Lavish883** [comment]
> can you share the code i want to make a graphql version of it

Yup I can do that I added you as a collaborator to that github repo. Again the code is a little messy so if u have any questions ask me.
